name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Run Super-Linter
      #   uses: github/super-linter@v3
      #   env:
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: npm run test

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install
        run: npm ci
      - name: build
        run: npm build
